services:
  postgres:
    image: 'postgres:latest'
    container_name: 'Motto.MD'  # Nome do contêiner
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_INITDB_ARGS=--encoding=UTF8'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - Motto.MD_Network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'

networks:
  Motto.MD_Network:

volumes:
  postgres_data:
