spring:
  application:
    name: Motto.MD
  jackson:
    default-property-inclusion: non_null

  datasource:
    url: jdbc:postgresql://DB_HOST:DB_PORT/DB_NAME
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG