spring:
  application:
    name: Motto.MD
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
server:
  port: 8080
